# Generated by Django 4.0.4 on 2022-05-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=500)),
                ('ProductBuy', models.CharField(max_length=500)),
                ('ProductSell', models.CharField(max_length=500)),
            ],
        ),
    ]
